<!-- Delete the sections that don't apply -->

### Backwards-incompatible changes

-

### New features

- The response to `GET /notebooks/:job_id` now includes an `ipynb_error` field that contains structured information about any exception that occurred when executing the notebook. As well, if an exception occurred, the resultant notebook is still included in the response. That is, notebook failures are no longer considered failed jobs.

- The `job_id` is now included in log messages when running the `nbexec` job under arq.

### Bug fixes

-

### Other changes

- Update to Python 3.12.
